# Generated by Django 5.0.11 on 2025-01-27 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education_certificates", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="date_earned",
            field=models.DateField(),
        ),
    ]
