# Generated by Django 5.0.11 on 2025-02-07 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("badge", models.ImageField(upload_to="technologies/")),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="QuickProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("date_completed", models.DateField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "thumbnail",
                    models.ImageField(upload_to="quick_projects/thumbnails/"),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "technologies_used",
                    models.ManyToManyField(
                        related_name="quick_projects", to="portfolio.technology"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeaturedProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("date_completed", models.DateField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "thumbnail",
                    models.ImageField(upload_to="featured_projects/thumbnails/"),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "technologies_used",
                    models.ManyToManyField(
                        related_name="featured_projects", to="portfolio.technology"
                    ),
                ),
            ],
        ),
    ]
