# Generated by Django 5.0.11 on 2025-02-07 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="featuredproject",
            options={
                "verbose_name": "Featured Project",
                "verbose_name_plural": "Featured Projects",
            },
        ),
        migrations.AlterModelOptions(
            name="quickproject",
            options={
                "verbose_name": "Quick Project",
                "verbose_name_plural": "Quick Projects",
            },
        ),
        migrations.AlterModelOptions(
            name="technology",
            options={
                "verbose_name": "Technology",
                "verbose_name_plural": "Technologies",
            },
        ),
        migrations.CreateModel(
            name="Screenshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="projects/screenshots/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screenshots",
                        to="portfolio.featuredproject",
                    ),
                ),
            ],
        ),
    ]
