# Generated by Django 5.0.11 on 2025-07-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_featuredproject_repository_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featuredproject",
            name="date_completed",
            field=models.DateField(blank=True, null=True),
        ),
    ]
