# Generated by Django 5.0.11 on 2025-07-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_alter_featuredproject_date_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featuredproject",
            name="date_created",
            field=models.DateField(auto_now_add=True),
        ),
    ]
